// <auto-generated />
using System;
using System.Collections.Generic;
using DirectoryServices.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DirectoryServices.Infrastructure.Migrations
{
    [DbContext(typeof(DirectoryServiceDbContext))]
    partial class DirectoryServicesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DirectoryServices.Domain.DepartmentManagement.Aggregate.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("parent_id")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("DepartmentName", "DirectoryServices.Domain.DepartmentManagement.Aggregate.Department.DepartmentName#DepartmentName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("department_name");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Depth", "DirectoryServices.Domain.DepartmentManagement.Aggregate.Department.Depth#Depth", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<short>("Value")
                                .HasColumnType("smallint")
                                .HasColumnName("depth");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Identifier", "DirectoryServices.Domain.DepartmentManagement.Aggregate.Department.Identifier#Identifier", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("identifier");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Path", "DirectoryServices.Domain.DepartmentManagement.Aggregate.Department.Path#Path", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("path");
                        });

                    b.HasKey("Id");

                    b.HasIndex("parent_id");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("DirectoryServices.Domain.DepartmentManagement.Supporting.DepartmentLocation", b =>
                {
                    b.Property<Guid>("DepartmentLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("department_id")
                        .HasColumnType("uuid");

                    b.HasKey("DepartmentLocationId")
                        .HasName("pk_department_location");

                    b.HasIndex("LocationId");

                    b.HasIndex("department_id");

                    b.ToTable("department_locations", (string)null);
                });

            modelBuilder.Entity("DirectoryServices.Domain.DepartmentManagement.Supporting.DepartmentPosition", b =>
                {
                    b.Property<Guid>("DepartmentPositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<Guid>("department_id")
                        .HasColumnType("uuid");

                    b.HasKey("DepartmentPositionId")
                        .HasName("pk_department_position");

                    b.HasIndex("PositionId");

                    b.HasIndex("department_id");

                    b.ToTable("department_positions", (string)null);
                });

            modelBuilder.Entity("DirectoryServices.Domain.LocationManagement.Aggregate.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty<Dictionary<string, object>>("Address", "DirectoryServices.Domain.LocationManagement.Aggregate.Location.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("country");

                            b1.Property<string>("HouseNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("house_number");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("region");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("street");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("LocationName", "DirectoryServices.Domain.LocationManagement.Aggregate.Location.LocationName#LocationName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("location_name");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Timezone", "DirectoryServices.Domain.LocationManagement.Aggregate.Location.Timezone#Timezone", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("timezone");
                        });

                    b.HasKey("Id");

                    b.ToTable("location", (string)null);
                });

            modelBuilder.Entity("DirectoryServices.Domain.PositionManagement.Aggregate.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "DirectoryServices.Domain.PositionManagement.Aggregate.Position.Description#Description", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("description");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PositionName", "DirectoryServices.Domain.PositionManagement.Aggregate.Position.PositionName#PositionName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("position_name");
                        });

                    b.HasKey("Id");

                    b.ToTable("position", (string)null);
                });

            modelBuilder.Entity("DirectoryServices.Domain.DepartmentManagement.Aggregate.Department", b =>
                {
                    b.HasOne("DirectoryServices.Domain.DepartmentManagement.Aggregate.Department", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("parent_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DirectoryServices.Domain.DepartmentManagement.Supporting.DepartmentLocation", b =>
                {
                    b.HasOne("DirectoryServices.Domain.LocationManagement.Aggregate.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DirectoryServices.Domain.DepartmentManagement.Aggregate.Department", "Department")
                        .WithMany("DepartmentLocations")
                        .HasForeignKey("department_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DirectoryServices.Domain.DepartmentManagement.Supporting.DepartmentPosition", b =>
                {
                    b.HasOne("DirectoryServices.Domain.PositionManagement.Aggregate.Position", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DirectoryServices.Domain.DepartmentManagement.Aggregate.Department", "Department")
                        .WithMany("DepartmentPositions")
                        .HasForeignKey("department_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DirectoryServices.Domain.DepartmentManagement.Aggregate.Department", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("DepartmentLocations");

                    b.Navigation("DepartmentPositions");
                });
#pragma warning restore 612, 618
        }
    }
}
